# Generated by Django 5.1.3 on 2024-12-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('artist_description', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
