# Generated by Django 5.1.3 on 2024-12-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_speciality_alter_makeup_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeup',
            name='image_url',
        ),
        migrations.AddField(
            model_name='makeup',
            name='image',
            field=models.FileField(null=True, upload_to='static/uploads'),
        ),
    ]
