# Generated by Django 5.1.3 on 2024-12-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_makeup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeup',
            name='artist_description',
            field=models.CharField(max_length=300),
        ),
    ]
