# Generated by Django 5.1.3 on 2024-12-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_makeup_artist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeup',
            name='image',
            field=models.FileField(null=True, upload_to='static/uploads'),
        ),
    ]
