# Generated by Django 5.1.3 on 2024-12-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_makeup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='speciality_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
