# Generated by Django 5.1.3 on 2025-03-25 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_makeup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeup',
            name='cover_pic',
            field=models.ImageField(blank=True, default='profilepic.png', null=True, upload_to='static/uploads/'),
        ),
        migrations.AddField(
            model_name='makeup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='makeup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='makeup',
            name='image',
            field=models.ImageField(blank=True, default='profilepic.png', null=True, upload_to='static/uploads'),
        ),
        migrations.CreateModel(
            name='ArtistPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ImageField(upload_to='static/portfolio/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='app.makeup')),
            ],
        ),
    ]
