# Generated by Django 5.1.3 on 2025-03-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_makeup_cover_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeup',
            name='artist_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
