# Generated by Django 5.1.3 on 2025-04-06 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_makeup_artist_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistportfolio',
            old_name='gallery',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='artistportfolio',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='artistportfolio',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='app.makeup'),
        ),
    ]
