# Generated by Django 5.1.3 on 2025-04-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_review'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='notification',
        #     name='is_read',
        # ),
    ]
