# Generated by Django 5.1.3 on 2025-04-20 14:51

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
            ),

    ]
