# Generated by Django 5.1.3 on 2025-01-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_profile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
    ]
