# Generated by Django 5.1.3 on 2025-03-31 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
