# Generated by Django 5.1.3 on 2025-04-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['timestamp']},
        ),
    ]
